plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
}

neoForge {
    version = '26.1.2.94'

    mods {
        zambielib {
            sourceSet sourceSets.main
        }
    }
}

base.archivesName = 'zambielib'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
